name: Сборка AOSP и MIUI ядер для Xiaomi 10

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        device: [umi]

    steps:
    - name: Проверка исходников
      uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - name: Очистка диска
      # Компиляция ядра не требует много места, но для большей безопасности рекомендуется удалить часть предустановленного программного обеспечения
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Установка зависимостей
      run: |
        sudo apt update
        sudo apt install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3 tar

    # Сгенерировать короткий хеш (исправить ошибку substr())
    - name: Установка короткого хеша SHA
      id: vars
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
      
    - name: Настройка Cache (ccache)
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache_mikernel
        key: ${{ runner.os }}-ccache-${{ matrix.device }}-${{ env.SHORT_SHA }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ matrix.device }}-
          ${{ runner.os }}-ccache-

    - name: Установка Toolchain (ZyC-Clang 15)
      run: |
        mkdir -p $HOME/zyc-clang
        cd $HOME/zyc-clang
        wget https://github.com/ZyCromerZ/Clang/releases/download/15.0.7-20251111-release/Clang-15.0.7-20251111.tar.gz
        tar -zxvf Clang-15.0.7-20251111.tar.gz
        cd $GITHUB_WORKSPACE

    - name: Сборка ядра для ${{ matrix.device }} (без NSU)
      run: |
        bash build.sh ${{ matrix.device }}

    - name: Сборка ядра для ${{ matrix.device }} (c NSU)
      run: |
        bash build.sh ${{ matrix.device }} nsu

    - name: Выгрузка архивов для ${{ matrix.device }}
      uses: actions/upload-artifact@v4
      with:
        name: aosp_miui-${{ matrix.device }}
        path: |
          AOSP_*.zip
          MIUI_*.zip
          
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Скачать все артефакты
      uses: actions/download-artifact@v4
      with:
        path: ./release_zips

    - name: Получение даты
      id: vars
      run: |
        echo "date=$(date +'%d_%m_%Y')" >> $GITHUB_OUTPUT

    - name: Отображение структуры загруженных файлов
        run: ls -R
    
    - name: Создать релиз на GitHub
      uses: softprops/action-gh-release@v2
      with:
        tag_name: Сборка от ${{ steps.vars.outputs.date }}
        name: "Сборка от ${{ steps.vars.outputs.date }}"
        body: "Автоматизированная сборка ядра для коммита ${{ env.SHORT_SHA }}
        files: ./release_zips/**/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
