name: Сборка ядра

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Выберите устройство'
        required: true
        default: 'umi'
        type: choice
        options:
          - psyche
          - umi
          - munch
          - lmi
          - cmi
          - cas
          - apollo
          - alioth
          - elish
          - enuma
          - dagu
          - pipa
      include_ksu:
        description: 'Включить SU (NextGenSU & SUSFS) в сборку'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Проверка исходников
      uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - name: Очистка диска
      # Компиляция ядра не требует много места, но для большей безопасности рекомендуется удалить часть предустановленного программного обеспечения
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Установка зависимостей
      run: |
        sudo apt update
        sudo apt install -y libselinux-dev build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3 tar

    # Сгенерировать короткий хеш (исправить ошибку substr())
    - name: Set short commit SHA
      id: vars
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: Настройка Cache (ccache)
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache_mikernel
        key: ${{ runner.os }}-ccache-${{ github.event.inputs.device }}-${{ github.event.inputs.include_ksu }}-${{ env.SHORT_SHA }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.event.inputs.device }}-${{ github.event.inputs.include_ksu }}-
          ${{ runner.os }}-ccache-${{ github.event.inputs.device }}-
          ${{ runner.os }}-ccache-

    - name: Установка Toolchain (ZyC-Clang 15)
      run: |
        mkdir -p $HOME/zyc-clang
        cd $HOME/zyc-clang
        wget https://github.com/ZyCromerZ/Clang/releases/download/15.0.7-20251111-release/Clang-15.0.7-20251111.tar.gz
        tar -zxvf Clang-15.0.7-20251111.tar.gz
        cd $GITHUB_WORKSPACE

    - name: Сборка ядра
      run: |
        if [ "${{ github.event.inputs.include_ksu }}" = "true" ]; then
          bash build.sh ${{ github.event.inputs.device }} ksu
        else
          bash build.sh ${{ github.event.inputs.device }}
        fi

    - name: Показать статистику кэширования
      run: ccache -s

    - name: Загрузка артефактов сборки
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.device }}${{ github.event.inputs.include_ksu == 'true' && '-ksu' || '' }}-kernel
        path: |
          MIUI_*.zip
          AOSP_*.zip
          out/arch/arm64/boot/Image
          out/arch/arm64/boot/dtb
